### ISSUE TITLE
Question about getConstPixel return value

### ISSUE THREAD

**Issue by leegee** [mash/node-imagemagick-native#68]
I was really pleased to find this module, but my lack of familiarity with the C API is letting me down  — please could you provide a little more info on the return value of getConstPixel? I realise the colour value relates to the quantum depth of my IM install, but am unsure who to convert the values to the format returned by the quantizeColors method.

Thanks in anticipation
Lee

**Comment by leegee** [comment]
OK — read the source and C API

**Comment by elad** [comment]
Hey, sorry for not picking this up earlier, I have very little time these days. :/ Do you feel like replying with a blurb that would have helped you for me to include in the documentation?
