### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by zhubofei** [mash/node-imagemagick-native#81]
> imagemagick-native@1.7.0 install /Users/zhubofei/imgmg/node_modules/imagemagick-native
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
/usr/local/bin/Magick++-config: line 53: pkg-config: command not found
/usr/local/bin/Magick++-config: line 56: pkg-config: command not found
gyp: Call to 'Magick++-config --ldflags --libs' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/zhubofei/imgmg/node_modules/imagemagick-native
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "imagemagick-native"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! imagemagick-native@1.7.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the imagemagick-native@1.7.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the imagemagick-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls imagemagick-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zhubofei/imgmg/npm-debug.log

**Comment by yosuke-furukawa** [comment]
next imagemagick-native will be solve this issue.
If you would like to solve the problem, you try to use the following command.

```
$ npm install git://github.com/mash/node-imagemagick-native.git
```

@mash @elad do you have a plan next release? and when??

**Comment by elad** [comment]
I just did.

I barely have time to fix and test everything so I hope it works out well...
