### ISSUE TITLE
Getting 'unhanded error' when using identify on a JPEG

### ISSUE THREAD

**Issue by visionscaper** [mash/node-imagemagick-native#89]
Hello,

I have a [JPEG file](https://dl.dropboxusercontent.com/u/9403467/share/my.jpg) that results in an 'unhandled error' when using imagemagick++'s identify through the imagemagick-native node module. However, when I simply use the command line version of identify, no error occurs.

Example node.js code that fails:

    fs.readFile('my.jpg', function(err, imageData) {
        imagemagick.identify({
            srcData         : imageData,
            debug           : true,
            ignoreWarnings  : false
        }, function (err, result) {
            console.log('err : ' + err.message);
            console.log('result : ' + JSON.stringify(result));
        });
    });

This results in 

    debug: on
    ignoreWarnings: 0
    err : unhandled error
    result : undefined

Just using the identify command:

    identify my.jpg
    my.jpg JPEG 2560x1280 2560x1280+0+0 8-bit sRGB 776KB 0.000u 0:00.000

I have tested the identify method through imagemagick-native (using the same node code snippet as above) with the sample parrot jpg. Identify does work with this file.

Is there anything I can do or check to resolve the issue?

Thanks,

 -- Freddy Snijder

PS : I'm on OS X Yosemite 10.10.3 and am using imagemagick 6.8.9-8

**Comment by visionscaper** [comment]
UPDATE:

Due to an error in my code the JPEG linked in my first message was missing 1 byte at the end of the file.
After resolving the issue, identify worked as expected. The robustness issue of imagemagick++ still stands however. I was really thrown off by the fact that the command line identify method worked.

**Comment by elad** [comment]
ImageMagick throws exceptions for both warnings and errors. Some warnings are silently ignored by the command line tool, but when using the API the code is required to catch and handle them explicitly. It could be that this is such a case - where an ignorable warning was simply not handled properly.

Could you please try with `ignoreWarnings` set to `true`?

**Comment by visionscaper** [comment]
Hi @elad Thanks for your responds. Unfortunately, I'm not getting any additional info when setting `ignoreWarnings` to `true`

    debug: on
    ignoreWarnings: 1
    err : unhandled error
    result : undefined

Cheers,

 -- Freddy

**Comment by pentode** [comment]
FWIW, using IM 6.8.9-9, I get a result on the truncated jpg file when setting ignoreWarnings: true.

@visionscaper did you install this module from github or the npm repository?  If you did install from npm repository could you update your dependency version to "mash/node-imagemagick-native" to install from github and try again?

I think it would be useful--and might become a requirement for me at some point--to collect the warning messages and return via the result object.
